# Generated by Django 3.0.5 on 2020-12-04 23:39

import apps.base.models.usercustom
import apps.base.rename_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyuser',
            name='username',
        ),
        migrations.AddField(
            model_name='pyuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default_avatar.png', max_length=255, null=True, storage=apps.base.rename_image.RenameImage(), upload_to=apps.base.models.usercustom.image_path),
        ),
        migrations.AddField(
            model_name='pyuser',
            name='day_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='pyuser',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Masculine'), ('U', 'Undefined')], default='U', max_length=64, verbose_name='Gender'),
        ),
    ]
