# Generated by Django 3.0.5 on 2020-12-26 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201224_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pymessage',
            name='conversation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.PyConversation'),
        ),
        migrations.AlterField(
            model_name='pymessage',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
