# Generated by Django 3.0.5 on 2021-01-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201225_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pycomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pymessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
